/// Contains the symbols, names, and Z numbers for all known elements.
///
/// # Note
///
/// Some Z number have multiple entries. This is to allow for querying based on
/// older, systematic names/symbols (like uuh), however a query of the Z number
/// should return the 'new', official name (livermorium or lv) This also allows
/// for different spellings of some names (cesium/caesium, aluminum/aluminium).
#[rustfmt::skip]
pub static DATA_TABLE : [(&str, i32, &str); 132] = [
    ("h",     1, "hydrogen"),      ("he",    2, "helium"),      ("li",    3, "lithium"),
    ("be",    4, "beryllium"),     ("b",     5, "boron"),       ("c",     6, "carbon"),
    ("n",     7, "nitrogen"),      ("o",     8, "oxygen"),      ("f",     9, "fluorine"),
    ("ne",   10, "neon"),          ("na",   11, "sodium"),      ("mg",   12, "magnesium"),
    ("al",   13, "aluminum"),      ("al",   13, "aluminium"),   ("si",   14, "silicon"),
    ("p",    15, "phosphorus"),    ("s",    16, "sulfur"),      ("cl",   17, "chlorine"),
    ("ar",   18, "argon"),         ("k",    19, "potassium"),   ("ca",   20, "calcium"),
    ("sc",   21, "scandium"),      ("ti",   22, "titanium"),    ("v",    23, "vanadium"),
    ("cr",   24, "chromium"),      ("mn",   25, "manganese"),   ("fe",   26, "iron"),
    ("co",   27, "cobalt"),        ("ni",   28, "nickel"),      ("cu",   29, "copper"),
    ("zn",   30, "zinc"),          ("ga",   31, "gallium"),     ("ge",   32, "germanium"),
    ("as",   33, "arsenic"),       ("se",   34, "selenium"),    ("br",   35, "bromine"),
    ("kr",   36, "krypton"),       ("rb",   37, "rubidium"),    ("sr",   38, "strontium"),
    ("y",    39, "yttrium"),       ("zr",   40, "zirconium"),   ("nb",   41, "niobium"),
    ("mo",   42, "molybdenum"),    ("tc",   43, "technetium"),  ("ru",   44, "ruthenium"),
    ("rh",   45, "rhodium"),       ("pd",   46, "palladium"),   ("ag",   47, "silver"),
    ("cd",   48, "cadmium"),       ("in",   49, "indium"),      ("sn",   50, "tin"),
    ("sb",   51, "antimony"),      ("te",   52, "tellurium"),   ("i",    53, "iodine"),
    ("xe",   54, "xenon"),         ("cs",   55, "cesium"),      ("cs",   55, "caesium"),
    ("ba",   56, "barium"),        ("la",   57, "lanthanum"),   ("ce",   58, "cerium"),
    ("pr",   59, "praseodymium"),  ("nd",   60, "neodymium"),   ("pm",   61, "promethium"),
    ("sm",   62, "samarium"),      ("eu",   63, "europium"),    ("gd",   64, "gadolinium"),
    ("tb",   65, "terbium"),       ("dy",   66, "dysprosium"),  ("ho",   67, "holmium"),
    ("er",   68, "erbium"),        ("tm",   69, "thulium"),     ("yb",   70, "ytterbium"),
    ("lu",   71, "lutetium"),      ("hf",   72, "hafnium"),     ("ta",   73, "tantalum"),
    ("w",    74, "tungsten"),      ("re",   75, "rhenium"),     ("os",   76, "osmium"),
    ("ir",   77, "iridium"),       ("pt",   78, "platinum"),    ("au",   79, "gold"),
    ("hg",   80, "mercury"),       ("tl",   81, "thallium"),    ("pb",   82, "lead"),
    ("bi",   83, "bismuth"),       ("po",   84, "polonium"),    ("at",   85, "astatine"),
    ("rn",   86, "radon"),         ("fr",   87, "francium"),    ("ra",   88, "radium"),
    ("ac",   89, "actinium"),      ("th",   90, "thorium"),     ("pa",   91, "protactinium"),
    ("u",    92, "uranium"),       ("np",   93, "neptunium"),   ("pu",   94, "plutonium"),
    ("am",   95, "americium"),     ("cm",   96, "curium"),      ("bk",   97, "berkelium"),
    ("cf",   98, "californium"),   ("es",   99, "einsteinium"), ("fm",  100, "fermium"),
    ("md",  101, "mendelevium"),   ("no",  102, "nobelium"),    ("lr",  103, "lawrencium"),
    ("rf",  104, "rutherfordium"), ("ha",  105, "hahnium"),     ("db",  105, "dubnium"),
    ("sg",  106, "seaborgium"),    ("bh",  107, "bohrium"),     ("hs",  108, "hassium"),
    ("mt",  109, "meitnerium"),    ("uun", 110, "ununnilium"),  ("ds",  110, "darmstadtium"),
    ("uuu", 111, "unununium"),     ("rg",  111, "roentgenium"), ("uub", 112, "ununbium"),
    ("cn",  112, "copernicium"),   ("uut", 113, "ununtrium"),   ("nh",  113, "nihonium"),
    ("uuq", 114, "ununquadium"),   ("fl",  114, "flerovium"),   ("uup", 115, "ununpentium"),
    ("mc",  115, "moscovium"),     ("uuh", 116, "ununhexium"),  ("lv",  116, "livermorium"),
    ("uus", 117, "ununseptium"),   ("ts",  117, "tennessine"),  ("uuo", 118, "ununoctium"),
    ("og",  118, "oganesson"),     ("uue", 119, "ununennium"),  ("ubn", 120, "unbinilium")
];

/// Maps Z (charge) to element data.
pub static ELEMENT_Z_MAP: phf::Map<i32, (&str, i32, &str)> = phf::phf_map! {
    1_i32 => ("h", 1, "hydrogen"),
    2_i32 => ("he", 2, "helium"),
    3_i32 => ("li", 3, "lithium"),
    4_i32 => ("be", 4, "beryllium"),
    5_i32 => ("b", 5, "boron"),
    6_i32 => ("c", 6, "carbon"),
    7_i32 => ("n", 7, "nitrogen"),
    8_i32 => ("o", 8, "oxygen"),
    9_i32 => ("f", 9, "fluorine"),
    10_i32 => ("ne", 10, "neon"),
    11_i32 => ("na", 11, "sodium"),
    12_i32 => ("mg", 12, "magnesium"),
    13_i32 => ("al", 13, "aluminium"),
    14_i32 => ("si", 14, "silicon"),
    15_i32 => ("p", 15, "phosphorus"),
    16_i32 => ("s", 16, "sulfur"),
    17_i32 => ("cl", 17, "chlorine"),
    18_i32 => ("ar", 18, "argon"),
    19_i32 => ("k", 19, "potassium"),
    20_i32 => ("ca", 20, "calcium"),
    21_i32 => ("sc", 21, "scandium"),
    22_i32 => ("ti", 22, "titanium"),
    23_i32 => ("v", 23, "vanadium"),
    24_i32 => ("cr", 24, "chromium"),
    25_i32 => ("mn", 25, "manganese"),
    26_i32 => ("fe", 26, "iron"),
    27_i32 => ("co", 27, "cobalt"),
    28_i32 => ("ni", 28, "nickel"),
    29_i32 => ("cu", 29, "copper"),
    30_i32 => ("zn", 30, "zinc"),
    31_i32 => ("ga", 31, "gallium"),
    32_i32 => ("ge", 32, "germanium"),
    33_i32 => ("as", 33, "arsenic"),
    34_i32 => ("se", 34, "selenium"),
    35_i32 => ("br", 35, "bromine"),
    36_i32 => ("kr", 36, "krypton"),
    37_i32 => ("rb", 37, "rubidium"),
    38_i32 => ("sr", 38, "strontium"),
    39_i32 => ("y", 39, "yttrium"),
    40_i32 => ("zr", 40, "zirconium"),
    41_i32 => ("nb", 41, "niobium"),
    42_i32 => ("mo", 42, "molybdenum"),
    43_i32 => ("tc", 43, "technetium"),
    44_i32 => ("ru", 44, "ruthenium"),
    45_i32 => ("rh", 45, "rhodium"),
    46_i32 => ("pd", 46, "palladium"),
    47_i32 => ("ag", 47, "silver"),
    48_i32 => ("cd", 48, "cadmium"),
    49_i32 => ("in", 49, "indium"),
    50_i32 => ("sn", 50, "tin"),
    51_i32 => ("sb", 51, "antimony"),
    52_i32 => ("te", 52, "tellurium"),
    53_i32 => ("i", 53, "iodine"),
    54_i32 => ("xe", 54, "xenon"),
    55_i32 => ("cs", 55, "caesium"),
    56_i32 => ("ba", 56, "barium"),
    57_i32 => ("la", 57, "lanthanum"),
    58_i32 => ("ce", 58, "cerium"),
    59_i32 => ("pr", 59, "praseodymium"),
    60_i32 => ("nd", 60, "neodymium"),
    61_i32 => ("pm", 61, "promethium"),
    62_i32 => ("sm", 62, "samarium"),
    63_i32 => ("eu", 63, "europium"),
    64_i32 => ("gd", 64, "gadolinium"),
    65_i32 => ("tb", 65, "terbium"),
    66_i32 => ("dy", 66, "dysprosium"),
    67_i32 => ("ho", 67, "holmium"),
    68_i32 => ("er", 68, "erbium"),
    69_i32 => ("tm", 69, "thulium"),
    70_i32 => ("yb", 70, "ytterbium"),
    71_i32 => ("lu", 71, "lutetium"),
    72_i32 => ("hf", 72, "hafnium"),
    73_i32 => ("ta", 73, "tantalum"),
    74_i32 => ("w", 74, "tungsten"),
    75_i32 => ("re", 75, "rhenium"),
    76_i32 => ("os", 76, "osmium"),
    77_i32 => ("ir", 77, "iridium"),
    78_i32 => ("pt", 78, "platinum"),
    79_i32 => ("au", 79, "gold"),
    80_i32 => ("hg", 80, "mercury"),
    81_i32 => ("tl", 81, "thallium"),
    82_i32 => ("pb", 82, "lead"),
    83_i32 => ("bi", 83, "bismuth"),
    84_i32 => ("po", 84, "polonium"),
    85_i32 => ("at", 85, "astatine"),
    86_i32 => ("rn", 86, "radon"),
    87_i32 => ("fr", 87, "francium"),
    88_i32 => ("ra", 88, "radium"),
    89_i32 => ("ac", 89, "actinium"),
    90_i32 => ("th", 90, "thorium"),
    91_i32 => ("pa", 91, "protactinium"),
    92_i32 => ("u", 92, "uranium"),
    93_i32 => ("np", 93, "neptunium"),
    94_i32 => ("pu", 94, "plutonium"),
    95_i32 => ("am", 95, "americium"),
    96_i32 => ("cm", 96, "curium"),
    97_i32 => ("bk", 97, "berkelium"),
    98_i32 => ("cf", 98, "californium"),
    99_i32 => ("es", 99, "einsteinium"),
    100_i32 => ("fm", 100, "fermium"),
    101_i32 => ("md", 101, "mendelevium"),
    102_i32 => ("no", 102, "nobelium"),
    103_i32 => ("lr", 103, "lawrencium"),
    104_i32 => ("rf", 104, "rutherfordium"),
    105_i32 => ("db", 105, "dubnium"),
    106_i32 => ("sg", 106, "seaborgium"),
    107_i32 => ("bh", 107, "bohrium"),
    108_i32 => ("hs", 108, "hassium"),
    109_i32 => ("mt", 109, "meitnerium"),
    110_i32 => ("ds", 110, "darmstadtium"),
    111_i32 => ("rg", 111, "roentgenium"),
    112_i32 => ("cn", 112, "copernicium"),
    113_i32 => ("nh", 113, "nihonium"),
    114_i32 => ("fl", 114, "flerovium"),
    115_i32 => ("mc", 115, "moscovium"),
    116_i32 => ("lv", 116, "livermorium"),
    117_i32 => ("ts", 117, "tennessine"),
    118_i32 => ("og", 118, "oganesson"),
    119_i32 => ("uue", 119, "ununennium"),
    120_i32 => ("ubn", 120, "unbinilium"),
};

/// Maps element symbol to element data.
pub static ELEMENT_SYM_MAP: phf::Map<&str, (&str, i32, &str)> = phf::phf_map! {
    "h" => ("h", 1, "hydrogen"),
    "he" => ("he", 2, "helium"),
    "li" => ("li", 3, "lithium"),
    "be" => ("be", 4, "beryllium"),
    "b" => ("b", 5, "boron"),
    "c" => ("c", 6, "carbon"),
    "n" => ("n", 7, "nitrogen"),
    "o" => ("o", 8, "oxygen"),
    "f" => ("f", 9, "fluorine"),
    "ne" => ("ne", 10, "neon"),
    "na" => ("na", 11, "sodium"),
    "mg" => ("mg", 12, "magnesium"),
    "al" => ("al", 13, "aluminium"),
    "si" => ("si", 14, "silicon"),
    "p" => ("p", 15, "phosphorus"),
    "s" => ("s", 16, "sulfur"),
    "cl" => ("cl", 17, "chlorine"),
    "ar" => ("ar", 18, "argon"),
    "k" => ("k", 19, "potassium"),
    "ca" => ("ca", 20, "calcium"),
    "sc" => ("sc", 21, "scandium"),
    "ti" => ("ti", 22, "titanium"),
    "v" => ("v", 23, "vanadium"),
    "cr" => ("cr", 24, "chromium"),
    "mn" => ("mn", 25, "manganese"),
    "fe" => ("fe", 26, "iron"),
    "co" => ("co", 27, "cobalt"),
    "ni" => ("ni", 28, "nickel"),
    "cu" => ("cu", 29, "copper"),
    "zn" => ("zn", 30, "zinc"),
    "ga" => ("ga", 31, "gallium"),
    "ge" => ("ge", 32, "germanium"),
    "as" => ("as", 33, "arsenic"),
    "se" => ("se", 34, "selenium"),
    "br" => ("br", 35, "bromine"),
    "kr" => ("kr", 36, "krypton"),
    "rb" => ("rb", 37, "rubidium"),
    "sr" => ("sr", 38, "strontium"),
    "y" => ("y", 39, "yttrium"),
    "zr" => ("zr", 40, "zirconium"),
    "nb" => ("nb", 41, "niobium"),
    "mo" => ("mo", 42, "molybdenum"),
    "tc" => ("tc", 43, "technetium"),
    "ru" => ("ru", 44, "ruthenium"),
    "rh" => ("rh", 45, "rhodium"),
    "pd" => ("pd", 46, "palladium"),
    "ag" => ("ag", 47, "silver"),
    "cd" => ("cd", 48, "cadmium"),
    "in" => ("in", 49, "indium"),
    "sn" => ("sn", 50, "tin"),
    "sb" => ("sb", 51, "antimony"),
    "te" => ("te", 52, "tellurium"),
    "i" => ("i", 53, "iodine"),
    "xe" => ("xe", 54, "xenon"),
    "cs" => ("cs", 55, "caesium"),
    "ba" => ("ba", 56, "barium"),
    "la" => ("la", 57, "lanthanum"),
    "ce" => ("ce", 58, "cerium"),
    "pr" => ("pr", 59, "praseodymium"),
    "nd" => ("nd", 60, "neodymium"),
    "pm" => ("pm", 61, "promethium"),
    "sm" => ("sm", 62, "samarium"),
    "eu" => ("eu", 63, "europium"),
    "gd" => ("gd", 64, "gadolinium"),
    "tb" => ("tb", 65, "terbium"),
    "dy" => ("dy", 66, "dysprosium"),
    "ho" => ("ho", 67, "holmium"),
    "er" => ("er", 68, "erbium"),
    "tm" => ("tm", 69, "thulium"),
    "yb" => ("yb", 70, "ytterbium"),
    "lu" => ("lu", 71, "lutetium"),
    "hf" => ("hf", 72, "hafnium"),
    "ta" => ("ta", 73, "tantalum"),
    "w" => ("w", 74, "tungsten"),
    "re" => ("re", 75, "rhenium"),
    "os" => ("os", 76, "osmium"),
    "ir" => ("ir", 77, "iridium"),
    "pt" => ("pt", 78, "platinum"),
    "au" => ("au", 79, "gold"),
    "hg" => ("hg", 80, "mercury"),
    "tl" => ("tl", 81, "thallium"),
    "pb" => ("pb", 82, "lead"),
    "bi" => ("bi", 83, "bismuth"),
    "po" => ("po", 84, "polonium"),
    "at" => ("at", 85, "astatine"),
    "rn" => ("rn", 86, "radon"),
    "fr" => ("fr", 87, "francium"),
    "ra" => ("ra", 88, "radium"),
    "ac" => ("ac", 89, "actinium"),
    "th" => ("th", 90, "thorium"),
    "pa" => ("pa", 91, "protactinium"),
    "u" => ("u", 92, "uranium"),
    "np" => ("np", 93, "neptunium"),
    "pu" => ("pu", 94, "plutonium"),
    "am" => ("am", 95, "americium"),
    "cm" => ("cm", 96, "curium"),
    "bk" => ("bk", 97, "berkelium"),
    "cf" => ("cf", 98, "californium"),
    "es" => ("es", 99, "einsteinium"),
    "fm" => ("fm", 100, "fermium"),
    "md" => ("md", 101, "mendelevium"),
    "no" => ("no", 102, "nobelium"),
    "lr" => ("lr", 103, "lawrencium"),
    "rf" => ("rf", 104, "rutherfordium"),
    "ha" => ("ha", 105, "hahnium"),
    "db" => ("db", 105, "dubnium"),
    "sg" => ("sg", 106, "seaborgium"),
    "bh" => ("bh", 107, "bohrium"),
    "hs" => ("hs", 108, "hassium"),
    "mt" => ("mt", 109, "meitnerium"),
    "uun" => ("uun", 110, "ununnilium"),
    "ds" => ("ds", 110, "darmstadtium"),
    "uuu" => ("uuu", 111, "unununium"),
    "rg" => ("rg", 111, "roentgenium"),
    "uub" => ("uub", 112, "ununbium"),
    "cn" => ("cn", 112, "copernicium"),
    "uut" => ("uut", 113, "ununtrium"),
    "nh" => ("nh", 113, "nihonium"),
    "uuq" => ("uuq", 114, "ununquadium"),
    "fl" => ("fl", 114, "flerovium"),
    "uup" => ("uup", 115, "ununpentium"),
    "mc" => ("mc", 115, "moscovium"),
    "uuh" => ("uuh", 116, "ununhexium"),
    "lv" => ("lv", 116, "livermorium"),
    "uus" => ("uus", 117, "ununseptium"),
    "ts" => ("ts", 117, "tennessine"),
    "uuo" => ("uuo", 118, "ununoctium"),
    "og" => ("og", 118, "oganesson"),
    "uue" => ("uue", 119, "ununennium"),
    "ubn" => ("ubn", 120, "unbinilium"),
};

/// Maps element name to element data.
pub static ELEMENT_NAME_MAP: phf::Map<&str, (&str, i32, &str)> = phf::phf_map! {
    "hydrogen" => ("h", 1, "hydrogen"),
    "helium" => ("he", 2, "helium"),
    "lithium" => ("li", 3, "lithium"),
    "beryllium" => ("be", 4, "beryllium"),
    "boron" => ("b", 5, "boron"),
    "carbon" => ("c", 6, "carbon"),
    "nitrogen" => ("n", 7, "nitrogen"),
    "oxygen" => ("o", 8, "oxygen"),
    "fluorine" => ("f", 9, "fluorine"),
    "neon" => ("ne", 10, "neon"),
    "sodium" => ("na", 11, "sodium"),
    "magnesium" => ("mg", 12, "magnesium"),
    "aluminum" => ("al", 13, "aluminum"),
    "aluminium" => ("al", 13, "aluminium"),
    "silicon" => ("si", 14, "silicon"),
    "phosphorus" => ("p", 15, "phosphorus"),
    "sulfur" => ("s", 16, "sulfur"),
    "chlorine" => ("cl", 17, "chlorine"),
    "argon" => ("ar", 18, "argon"),
    "potassium" => ("k", 19, "potassium"),
    "calcium" => ("ca", 20, "calcium"),
    "scandium" => ("sc", 21, "scandium"),
    "titanium" => ("ti", 22, "titanium"),
    "vanadium" => ("v", 23, "vanadium"),
    "chromium" => ("cr", 24, "chromium"),
    "manganese" => ("mn", 25, "manganese"),
    "iron" => ("fe", 26, "iron"),
    "cobalt" => ("co", 27, "cobalt"),
    "nickel" => ("ni", 28, "nickel"),
    "copper" => ("cu", 29, "copper"),
    "zinc" => ("zn", 30, "zinc"),
    "gallium" => ("ga", 31, "gallium"),
    "germanium" => ("ge", 32, "germanium"),
    "arsenic" => ("as", 33, "arsenic"),
    "selenium" => ("se", 34, "selenium"),
    "bromine" => ("br", 35, "bromine"),
    "krypton" => ("kr", 36, "krypton"),
    "rubidium" => ("rb", 37, "rubidium"),
    "strontium" => ("sr", 38, "strontium"),
    "yttrium" => ("y", 39, "yttrium"),
    "zirconium" => ("zr", 40, "zirconium"),
    "niobium" => ("nb", 41, "niobium"),
    "molybdenum" => ("mo", 42, "molybdenum"),
    "technetium" => ("tc", 43, "technetium"),
    "ruthenium" => ("ru", 44, "ruthenium"),
    "rhodium" => ("rh", 45, "rhodium"),
    "palladium" => ("pd", 46, "palladium"),
    "silver" => ("ag", 47, "silver"),
    "cadmium" => ("cd", 48, "cadmium"),
    "indium" => ("in", 49, "indium"),
    "tin" => ("sn", 50, "tin"),
    "antimony" => ("sb", 51, "antimony"),
    "tellurium" => ("te", 52, "tellurium"),
    "iodine" => ("i", 53, "iodine"),
    "xenon" => ("xe", 54, "xenon"),
    "cesium" => ("cs", 55, "cesium"),
    "caesium" => ("cs", 55, "caesium"),
    "barium" => ("ba", 56, "barium"),
    "lanthanum" => ("la", 57, "lanthanum"),
    "cerium" => ("ce", 58, "cerium"),
    "praseodymium" => ("pr", 59, "praseodymium"),
    "neodymium" => ("nd", 60, "neodymium"),
    "promethium" => ("pm", 61, "promethium"),
    "samarium" => ("sm", 62, "samarium"),
    "europium" => ("eu", 63, "europium"),
    "gadolinium" => ("gd", 64, "gadolinium"),
    "terbium" => ("tb", 65, "terbium"),
    "dysprosium" => ("dy", 66, "dysprosium"),
    "holmium" => ("ho", 67, "holmium"),
    "erbium" => ("er", 68, "erbium"),
    "thulium" => ("tm", 69, "thulium"),
    "ytterbium" => ("yb", 70, "ytterbium"),
    "lutetium" => ("lu", 71, "lutetium"),
    "hafnium" => ("hf", 72, "hafnium"),
    "tantalum" => ("ta", 73, "tantalum"),
    "tungsten" => ("w", 74, "tungsten"),
    "rhenium" => ("re", 75, "rhenium"),
    "osmium" => ("os", 76, "osmium"),
    "iridium" => ("ir", 77, "iridium"),
    "platinum" => ("pt", 78, "platinum"),
    "gold" => ("au", 79, "gold"),
    "mercury" => ("hg", 80, "mercury"),
    "thallium" => ("tl", 81, "thallium"),
    "lead" => ("pb", 82, "lead"),
    "bismuth" => ("bi", 83, "bismuth"),
    "polonium" => ("po", 84, "polonium"),
    "astatine" => ("at", 85, "astatine"),
    "radon" => ("rn", 86, "radon"),
    "francium" => ("fr", 87, "francium"),
    "radium" => ("ra", 88, "radium"),
    "actinium" => ("ac", 89, "actinium"),
    "thorium" => ("th", 90, "thorium"),
    "protactinium" => ("pa", 91, "protactinium"),
    "uranium" => ("u", 92, "uranium"),
    "neptunium" => ("np", 93, "neptunium"),
    "plutonium" => ("pu", 94, "plutonium"),
    "americium" => ("am", 95, "americium"),
    "curium" => ("cm", 96, "curium"),
    "berkelium" => ("bk", 97, "berkelium"),
    "californium" => ("cf", 98, "californium"),
    "einsteinium" => ("es", 99, "einsteinium"),
    "fermium" => ("fm", 100, "fermium"),
    "mendelevium" => ("md", 101, "mendelevium"),
    "nobelium" => ("no", 102, "nobelium"),
    "lawrencium" => ("lr", 103, "lawrencium"),
    "rutherfordium" => ("rf", 104, "rutherfordium"),
    "hahnium" => ("ha", 105, "hahnium"),
    "dubnium" => ("db", 105, "dubnium"),
    "seaborgium" => ("sg", 106, "seaborgium"),
    "bohrium" => ("bh", 107, "bohrium"),
    "hassium" => ("hs", 108, "hassium"),
    "meitnerium" => ("mt", 109, "meitnerium"),
    "ununnilium" => ("uun", 110, "ununnilium"),
    "darmstadtium" => ("ds", 110, "darmstadtium"),
    "unununium" => ("uuu", 111, "unununium"),
    "roentgenium" => ("rg", 111, "roentgenium"),
    "ununbium" => ("uub", 112, "ununbium"),
    "copernicium" => ("cn", 112, "copernicium"),
    "ununtrium" => ("uut", 113, "ununtrium"),
    "nihonium" => ("nh", 113, "nihonium"),
    "ununquadium" => ("uuq", 114, "ununquadium"),
    "flerovium" => ("fl", 114, "flerovium"),
    "ununpentium" => ("uup", 115, "ununpentium"),
    "moscovium" => ("mc", 115, "moscovium"),
    "ununhexium" => ("uuh", 116, "ununhexium"),
    "livermorium" => ("lv", 116, "livermorium"),
    "ununseptium" => ("uus", 117, "ununseptium"),
    "tennessine" => ("ts", 117, "tennessine"),
    "ununoctium" => ("uuo", 118, "ununoctium"),
    "oganesson" => ("og", 118, "oganesson"),
    "ununennium" => ("uue", 119, "ununennium"),
    "unbinilium" => ("ubn", 120, "unbinilium"),
};

/// Maps angular momentum characters to integers (the integer is the index of
/// the character in this string) This is the 'hik' convention, where AM=7 is k.
pub const AMCHAR_MAP_HIK: &str = "spdfghiklmnoqrtuvwxyzabce";

/// Maps angular momentum characters to integers (the integer is the index of
/// the character in this string) This is the 'hij' convention, where AM=7 is j.
pub const AMCHAR_MAP_HIJ: &str = "spdfghijklmnoqrtuvwxyzabce";
